- name: Check Deployment Summary
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/apps.yml
    - vars/plan.yml

  tasks:
    - name: "{{ lookup('pipe', 'date +%H:%M:%S') }} | localhost | Master | Deployment Summary"
      include_tasks: _deploy_summary.yml
