- name: Master Orchestration
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/apps.yml
    - vars/plan.yml

  tasks:
    - name: "{{ lookup('pipe', 'date +%H:%M:%S') }} | localhost | Master | Starting Deployment Sequence (Total Groups: {{ deployment_plan | length }})"
      debug:
        msg: "Plan loaded. Starting grouped execution..."

    # 循环读取 Group 计划表
    - name: "{{ lookup('pipe', 'date +%H:%M:%S') }} | localhost | Master | Process Deployment Groups"
      include_tasks: _process_group.yml
      loop: "{{ deployment_plan }}"
      loop_control:
        loop_var: group_item