- name: Master Orchestration
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/apps.yml
    - vars/plan.yml

  tasks:
    - name: "Starting Deployment Sequence (Total Groups: {{ deploy_groups | length }})"
      debug:
        msg: "Plan loaded. Starting grouped execution..."

    # 循环读取 Group 计划表
    - name: Process Deployment Groups
      include_tasks: _process_group.yml
      loop: "{{ deploy_groups }}"
      loop_control:
        loop_var: group_item