- name: Master Orchestration
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/apps.yml

  vars:
    plans:
      - vars/plan.yml

  tasks:
    - name: "{{ lookup('pipe', 'date +%H:%M:%S') }} | localhost | Master | Starting Deployment Sequence"
      debug:
        msg: "Master Orchestration started. Iterating over plans: {{ plans }}"

    - name: "{{ lookup('pipe', 'date +%H:%M:%S') }} | localhost | Master | Process Plans"
      include_tasks: _process_plan.yml
      loop: "{{ plans }}"
      loop_control:
        loop_var: plan_file